# Server config
server:
  port: ${PORT:8765}

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

info:
  component: API Gateway

# Spring config
spring:
  application:
    name: api-gateway

# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
    registerWithEureka: false

# Ribbon config
ribbon:
  eureka:
    enabled: true

# Zuul config
zuul:
  prefix: /api/v1
  routes:
    users:
      path: /users/**
      serviceId: user-service
    vehicles:
      path: /vehicles/**
      serviceId: vehicle-service
    zones:
      path: /zones/**
      serviceId: zone-service
    bookings:
      path: /bookings/**
      serviceId: booking-service
    help:
      path: /help/**
      serviceId: help-service
    reports:
      path: /reports/**
      serviceId: report-service

endpoints:
  routes:
    sensitive: false
