export const environment = {
  production: true,
  baseUrl: 'http://172.23.234.83:8091/',
  userService: 'user-service',
  userBaseApi: '/api/v1/users',
  baseUrl1: 'http://localhost:8093/',
  zoneService: 'zone-service',
  zoneBaseApi: '/api/v1/zones',
  baseUrl2: 'http://localhost:8093/',
  campaignService: 'campaign-service',
  campaignBaseApi: '/api/v1/campaigns',
  vehicleService: 'vehicle-service',
  vehicleBaseApi: '/api/v1/vehicles',
  typeBaseApi: '/api/v1/types',
  fuelBaseApi: '/api/v1/fuel',
};
