version: "3"

services:

  # mongodb
  mongo:
    image: mongo
    container_name: 'umove-mongodb'
#    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'root'
    volumes:
      - '/home/vishnu/Desktop/Assignments/umove/data/mongo:/data/db'

  # rabbitmq
  rabbit:
    image: 'rabbitmq:3-management'
    container_name: 'umove-rabbitmq'
#    restart: always
    hostname: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: 'root'
      RABBITMQ_DEFAULT_PASS: 'root'
      RABBITMQ_DEFAULT_VHOST: '/'
    ports:
      - '15672:15672'
      - '5672:5672'
