# Server config
server:
  port: ${PORT:8761}

# Spring config
spring:
  application:
    name: discovery-service

# Eureka config
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/